name: 'Terraform CI/CD'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        run: terraform -chdir=environments/dev init -input=false

      - name: Terraform Format Check
        run: terraform -chdir=environments/dev fmt -check

      - name: Terraform Validate
        run: terraform -chdir=environments/dev validate -input=false

      - name: Terraform Plan
        run: terraform -chdir=environments/dev plan -input=false

  apply:
    if: github.event_name == 'push'
    needs: validate
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        run: terraform -chdir=environments/dev init -input=false

      - name: Terraform Apply
        run: terraform -chdir=environments/dev apply -input=false -auto-approve
